### ISSUE TITLE
RuntimeError: only batches of spatial targets supported (3D tensors) but got targets of size: : [8, 1, 224, 224]

### ISSUE THREAD

**Issue by soni-H** [HSG-AIML/SSLTransformerRS#1]
I am trying to evaluate the segmentation task using the command-

python train_evaluation.py --model=DoubleSwinTransformerSegmentation --image_px_size=224 --batch_size=8 --checkpoint=checkpoints/swin_t.pth --target dfc

There seems to some error when the code tries to find CrossEntropyLoss. Error says-
RuntimeError: only batches of spatial targets supported (3D tensors) but got targets of size: : [8, 1, 224, 224]

The dimensions of y and y_hat are different. 

y_hat shape is  torch.Size([8, 8, 224, 224])
y shape is  torch.Size([8, 1, 224, 224])

**Comment by joellehanna** [comment]
Hi! thanks for pointing it out, it should be fixed now.
