### ISSUE TITLE
where can I get these files mentioned here?

### ISSUE THREAD

**Issue by fangwei00-jin** [HSG-AIML/SSLTransformerRS#2]
"**_observations_balanced_classes.csv**" or "**_observations.csv**"
I couldn't find any information about them in the dataset [DFC2020](https://ieee-dataport.org/competitions/2020-ieee-grss-data-fusion-contest#files) (downstream land-cover classification/segmentation)

https://github.com/HSG-AIML/SSLTransformerRS/blob/ad04805e405cdc60ef984c66ecea7098bf691994/dfc_dataset.py#L169

https://github.com/HSG-AIML/SSLTransformerRS/blob/ad04805e405cdc60ef984c66ecea7098bf691994/dfc_dataset.py#L175

**Comment by scheibenreif** [comment]
Hi @fangwei00-jin thanks for your question!
These files are part of the repository - you can find them in the [splits](https://github.com/HSG-AIML/SSLTransformerRS/tree/main/splits) directory.

Best,
Linus
