### ISSUE TITLE
CUDA Compatibility with PyTorch 1.11

### ISSUE THREAD

**Issue by chandlerbing65nm** [HSG-AIML/SSLTransformerRS#3]
Hello! I was wondering if you could share with me the version of CUDA that you used when working with PyTorch 1.11 in your Python scripts. I am just trying to get a sense of which versions are compatible and any insight you have would be greatly appreciated.

**Comment by joellehanna** [comment]
Hi, the CUDA version used is 11.4.

**Comment by chandlerbing65nm** [comment]
> Hi, the CUDA version used is 11.4.

@joellehanna97 Is it 11.4 or 11.3? I can't find cuda11.4 in pytorch and docker.

**Comment by joellehanna** [comment]
My bad, we're actually using cuda 11.5
