### ISSUE TITLE
How to train with my own data

### ISSUE THREAD

**Issue by chandlerbing65nm** [HSG-AIML/SSLTransformerRS#4]
I would like to use my worldview-1/2 images to train your model for SSL pre-training. Could you tell me how you prepared the sentinel-1/2 data?

**Comment by chandlerbing65nm** [comment]
Can anyone help? @damianborth @joellehanna97 @mommermi @scheibenreif

**Comment by scheibenreif** [comment]
Hi @chandlerbing65nm 

our dataloader is specific to the SEN12MS/DFC2020 dataset - for other datasets you'll have to replace it with your own loader. That should be fairly straightforward through, just make sure that __getitem__ returns the two modalities in a dict with keys `s1` and `s2`.

Best,

Linus

**Comment by rongtongxueya** [comment]
I also have some confusion about the data set replaced with my own, but I still want to use Sentinel-1 and Sentinel-2 data, but I see that your data is cut into 224, is this the best size? Or have you tried other image sizes
